const mods = [
  {
    id: "scripthookv",
    name: "ScriptHookV",
    description: "Library that makes it possible to use scripts in GTA V. Essential for most script mods.",
    author: "Alexander Blade",
    category: "Tools",
    version: "v1.0.2635.0",
    downloads: 15420,
    likes: 8920,
    url: "https://www.gta5-mods.com/tools/script-hook-v",
    downloadUrl: "https://github.com/alexblade1/ScriptHookV/releases/latest",
    image: "https://i.imgur.com/8xGQJ2Y.png",
    tags: ["tool", "scripting", "essential"],
    featured: true,
    lastUpdated: "2025-11-25"
  },
  {
    id: "visualv",
    name: "VisualV",
    description: "Complete visual overhaul mod with enhanced graphics, weather, lighting, and effects.",
    author: "CP",
    category: "Graphics",
    version: "v1.0.600",
    downloads: 12850,
    likes: 7650,
    url: "https://www.gta5-mods.com/graphics/visualv",
    downloadUrl: "https://www.gta5-mods.com/downloads/visualv",
    image: "https://i.imgur.com/9LqYcTf.png",
    tags: ["graphics", "visual", "weather"],
    featured: true,
    lastUpdated: "2025-11-25"
  },
  {
    id: "lspdfr",
    name: "LSPDFR",
    description: "Police roleplay mod that lets you play as a police officer in GTA V.",
    author: "G17 Media",
    category: "Scripts",
    version: "v0.4.11",
    downloads: 25680,
    likes: 12400,
    url: "https://www.lcpdfr.com/downloads/gta5mods/lspdfr",
    downloadUrl: "https://www.lcpdfr.com/downloads/gta5mods/lspdfr",
    image: "https://i.imgur.com/FgKXmVp.png",
    tags: ["police", "roleplay", "scripts"],
    featured: true,
    lastUpdated: "2025-11-25"
  },
  {
    id: "naturalvision",
    name: "NaturalVision Evolved",
    description: "Photorealistic graphics overhaul with stunning visuals and environmental improvements.",
    author: "Razed",
    category: "Graphics",
    version: "v1.0",
    downloads: 18920,
    likes: 9800,
    url: "https://www.gta5-mods.com/graphics/naturalvision-evolved",
    downloadUrl: "https://www.patreon.com/razed",
    image: "https://i.imgur.com/H7LkzQ9.png",
    tags: ["graphics", "photorealistic", "environment"],
    featured: true,
    lastUpdated: "2025-11-25"
  },
  {
    id: "fivem",
    name: "FiveM",
    description: "Multiplayer framework for GTA V with custom servers and scripting capabilities.",
    author: "FiveM Team",
    category: "Multiplayer",
    version: "latest",
    downloads: 45600,
    likes: 22300,
    url: "https://fivem.net/",
    downloadUrl: "https://fivem.net/",
    image: "https://i.imgur.com/8QG7Z2L.png",
    tags: ["multiplayer", "framework", "servers"],
    featured: true,
    lastUpdated: "2025-11-25"
  },
  {
    id: "openiv",
    name: "OpenIV",
    description: "Multi-purpose editor for GTA V files with archive management and modding tools.",
    author: "OpenIV Team",
    category: "Tools",
    version: "v4.0",
    downloads: 19800,
    likes: 10200,
    url: "https://openiv.com/",
    downloadUrl: "https://openiv.com/",
    image: "https://i.imgur.com/4D3f8hR.png",
    tags: ["tool", "editor", "archives"],
    featured: true,
    lastUpdated: "2025-11-25"
  },
  {
    id: "redux",
    name: "Redux",
    description: "Complete game overhaul with enhanced graphics, gameplay improvements, and new features.",
    author: "Josh Rom",
    category: "Graphics",
    version: "v2.5",
    downloads: 22100,
    likes: 11500,
    url: "https://www.gta5-mods.com/graphics/redux",
    downloadUrl: "https://www.gta5-mods.com/downloads/redux",
    image: "https://i.imgur.com/6YmK3pL.png",
    tags: ["graphics", "overhaul", "gameplay"],
    featured: true,
    lastUpdated: "2025-11-25"
  },
  {
    id: "mapbuilder",
    name: "Map Builder",
    description: "Tool for creating custom maps and objects in GTA V with easy-to-use interface.",
    author: "Guadmaz",
    category: "Tools",
    version: "v4.1",
    downloads: 5420,
    likes: 3200,
    url: "https://www.gta5-mods.com/scripts/map-builder",
    downloadUrl: "https://www.gta5-mods.com/downloads/map-builder",
    image: "https://i.imgur.com/7PqR8sN.png",
    tags: ["tool", "mapping", "creation"],
    featured: false,
    lastUpdated: "2025-11-25"
  },
  {
    id: "realisticdriving",
    name: "Realistic Driving V",
    description: "Realistic driving physics and handling improvements for all vehicles.",
    author: "Killatomate",
    category: "Scripts",
    version: "v5.8",
    downloads: 7650,
    likes: 4100,
    url: "https://www.gta5-mods.com/scripts/realistic-driving-v",
    downloadUrl: "https://www.gta5-mods.com/downloads/realistic-driving-v",
    image: "https://i.imgur.com/3JmK9hQ.png",
    tags: ["driving", "physics", "realism"],
    featured: false,
    lastUpdated: "2025-11-25"
  },
  {
    id: "enhancedtrainer",
    name: "Enhanced Native Trainer",
    description: "Feature-rich trainer with spawning, customization, and debugging tools.",
    author: "Enhanced Native Trainer Team",
    category: "Scripts",
    version: "v6.6",
    downloads: 8920,
    likes: 5200,
    url: "https://www.gta5-mods.com/scripts/enhanced-native-trainer",
    downloadUrl: "https://www.gta5-mods.com/downloads/enhanced-native-trainer",
    image: "https://i.imgur.com/5NqL8pM.png",
    tags: ["trainer", "tools", "spawning"],
    featured: false,
    lastUpdated: "2025-11-25"
  },
  {
    id: "worldofvariety",
    name: "World of Variety",
    description: "Adds variety to GTA V world with new vehicles, peds, and environmental details.",
    author: "Lundy",
    category: "Vehicles",
    version: "v8.0",
    downloads: 12400,
    likes: 6800,
    url: "https://www.gta5-mods.com/vehicles/world-of-variety",
    downloadUrl: "https://www.gta5-mods.com/downloads/world-of-variety",
    image: "https://i.imgur.com/9TqR3sN.png",
    tags: ["vehicles", "variety", "world"],
    featured: false,
    lastUpdated: "2025-11-25"
  },
  {
    id: "vanillaworks",
    name: "VanillaWorks",
    description: "Large vehicle pack with high-quality vanilla-style cars and trucks.",
    author: "VanillaWorks Team",
    category: "Vehicles",
    version: "v1.4",
    downloads: 9800,
    likes: 5400,
    url: "https://www.gta5-mods.com/vehicles/vanillaworks",
    downloadUrl: "https://www.gta5-mods.com/downloads/vanillaworks",
    image: "https://i.imgur.com/2KmP8hQ.png",
    tags: ["vehicles", "cars", "pack"],
    featured: false,
    lastUpdated: "2025-11-25"
  },
  {
    id: "gtarealism",
    name: "GTA Realism",
    description: "Realism mod with improved physics, combat, and environmental interactions.",
    author: "J1074",
    category: "Gameplay",
    version: "v5.4",
    downloads: 6700,
    likes: 3900,
    url: "https://www.gta5-mods.com/gameplay/gta-realism",
    downloadUrl: "https://www.gta5-mods.com/downloads/gta-realism",
    image: "https://i.imgur.com/4LqR9sN.png",
    tags: ["realism", "gameplay", "physics"],
    featured: false,
    lastUpdated: "2025-11-25"
  },
  {
    id: "ragepluginhook",
    name: "RAGE Plugin Hook",
    description: "Plugin framework for GTA V that enables advanced scripting capabilities.",
    author: "RAGE Plugin Hook Team",
    category: "Tools",
    version: "v1.104",
    downloads: 15200,
    likes: 8100,
    url: "https://www.ragepluginhook.net/",
    downloadUrl: "https://www.ragepluginhook.net/",
    image: "https://i.imgur.com/7MqR8sN.png",
    tags: ["tool", "plugin", "framework"],
    featured: false,
    lastUpdated: "2025-11-25"
  },
  {
    id: "buildamission",
    name: "Build a Mission",
    description: "Mission creator tool that allows you to design custom missions.",
    author: "Mafins",
    category: "Tools",
    version: "v1.6",
    downloads: 4300,
    likes: 2800,
    url: "https://www.gta5-mods.com/tools/build-a-mission",
    downloadUrl: "https://www.gta5-mods.com/downloads/build-a-mission",
    image: "https://i.imgur.com/8KqR9sN.png",
    tags: ["tool", "missions", "creator"],
    featured: false,
    lastUpdated: "2025-11-25"
  },
  {
    id: "modsuniversemenu",
    name: "ModsuniverseMenu Final",
    description: "Comprehensive mod menu with various features for single-player experimentation.",
    author: "ModsUniverse",
    category: "Tools",
    version: "v1.0",
    downloads: 12500,
    likes: 6800,
    url: "https://www.gta5-mods.com/mods/modsuniversemenu-final",
    downloadUrl: "https://files.gta5-mods.com/uploads/modsuniversemenu-0-25/202545-ModsuniverseMenu%20v1.0.rar",
    image: "https://i.imgur.com/9QmR8sN.png",
    tags: ["menu", "tools", "singleplayer"],
    featured: false,
    lastUpdated: "2025-11-25"
  },
  {
    id: "mysterioussp",
    name: "MysteriousSP",
    description: "Single-player mod menu with various customization options and tools.",
    author: "Mysterious",
    category: "Tools",
    version: "latest",
    downloads: 8900,
    likes: 4200,
    url: "https://www.gta5-mods.com/mods/mysterioussp",
    downloadUrl: "https://files.gta5-mods.com/uploads/mysterioussp/3f8a14-MysteriousSP.rar",
    image: "https://i.imgur.com/2LmP9hQ.png",
    tags: ["menu", "tools", "singleplayer"],
    featured: false,
    lastUpdated: "2025-11-25"
  },
  {
    id: "callensmenu",
    name: "Callen's Menu",
    description: "Single-player mod menu with extensive features for gameplay modification.",
    author: "Callen",
    category: "Tools",
    version: "1.0.1.0",
    downloads: 15600,
    likes: 7800,
    url: "https://www.gta5-mods.com/mods/callen-s-gta-v-single-player-mod-menu",
    downloadUrl: "https://files.gta5-mods.com/uploads/callen-s-gta-v-single-player-mod-menu/0ca820-Callen's%20SPMM%201.0.1.0.rar",
    image: "https://i.imgur.com/5KqR9sN.png",
    tags: ["menu", "tools", "singleplayer"],
    featured: false,
    lastUpdated: "2025-11-25"
  },
  {
    id: "menyoo2",
    name: "Menyoo 2.0",
    description: "Popular single-player trainer with extensive customization and spawning options.",
    author: "Menyoo Team",
    category: "Tools",
    version: "2.0",
    downloads: 28900,
    likes: 14200,
    url: "https://www.gta5-mods.com/mods/menyoo-2-0",
    downloadUrl: "https://files.gta5-mods.com/uploads/menyoo-2-0/b8996f-MenyooSP.zip",
    image: "https://i.imgur.com/8LqR9sN.png",
    tags: ["trainer", "menu", "tools", "singleplayer"],
    featured: true,
    lastUpdated: "2025-11-25"
  },
  {
    id: "rampagetrainer",
    name: "Rampage Trainer",
    description: "Legacy trainer with essential features for single-player experimentation.",
    author: "Rampage Team",
    category: "Tools",
    version: "1.0.3586.0",
    downloads: 9800,
    likes: 5100,
    url: "https://www.gta5-mods.com/mods/rampage-trainer",
    downloadUrl: "https://files.gta5-mods.com/uploads/rampage-trainer/63208d-Rampage_Legacy_1.0.3586.0.zip",
    image: "https://i.imgur.com/3MqR9sN.png",
    tags: ["trainer", "tools", "legacy", "singleplayer"],
    featured: false,
    lastUpdated: "2025-11-25"
  },
  {
    id: "enhancedtrainerlegacy",
    name: "[Legacy Only] Enhanced Native Trainer",
    description: "Legacy version of the popular trainer for older GTA V builds.",
    author: "Zemanez and others",
    category: "Tools",
    version: "Update 56",
    downloads: 11200,
    likes: 6300,
    url: "https://www.gta5-mods.com/mods/enhanced-native-trainer-zemanez-and-others",
    downloadUrl: "https://files.gta5-mods.com/uploads/enhanced-native-trainer-zemanez-and-others/ca9f28-Enhanced%20Native%20Trainer%20Update%2056.zip",
    image: "https://i.imgur.com/7NqR9sN.png",
    tags: ["trainer", "tools", "legacy", "singleplayer"],
    featured: false,
    lastUpdated: "2025-11-25"
  },
  {
    id: "menyoopc",
    name: "Menyoo PC [DEPRECATED]",
    description: "Deprecated version of Menyoo trainer - use Menyoo 2.0 instead.",
    author: "Menyoo Team",
    category: "Tools",
    version: "deprecated",
    downloads: 4500,
    likes: 2200,
    url: "https://www.gta5-mods.com/mods/menyoo-2-0",
    downloadUrl: "https://files.gta5-mods.com/uploads/menyoo-2-0/b8996f-MenyooSP.zip",
    image: "https://i.imgur.com/4KqR9sN.png",
    tags: ["trainer", "menu", "tools", "deprecated", "singleplayer"],
    featured: false,
    lastUpdated: "2025-11-25"
  }
];

module.exports = mods;
